In [2]:
import tensorflow as tf

In [14]:
# Matrix를 사용하지 않으면 스파게티 코드가 된다

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 99., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = x1 * w1 + x2 * 22 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {x1 : x1_data, x2 : x2_data, x3 : x3_data, Y : y_data})
    
    if step % 10 == 0 :
        print(step, "Cost : ", cost_val, "\nPrediction : \n" , hy_val)

0 Cost :  2.63104e+06 
Prediction : 
 [ 1644.15124512  2030.89050293  1861.09619141  2003.86853027  1336.53820801]
10 Cost :  11040.6 
Prediction : 
 [ 290.64221191  330.03942871  224.19059753  211.33494568   29.05400276]
20 Cost :  8617.44 
Prediction : 
 [ 249.48487854  278.34378052  174.4289093   156.8150177   -10.65751266]
30 Cost :  8613.32 
Prediction : 
 [ 248.22277832  276.78186035  172.91625977  155.13037109  -11.82904625]
40 Cost :  8611.45 
Prediction : 
 [ 248.17364502  276.74420166  172.87036133  155.05194092  -11.82885551]
50 Cost :  8609.58 
Prediction : 
 [ 248.16139221  276.75292969  172.86921692  155.02259827  -11.79301834]
60 Cost :  8607.72 
Prediction : 
 [ 248.15010071  276.76296997  172.86921692  154.99427795  -11.75632668]
70 Cost :  8605.85 
Prediction : 
 [ 248.13900757  276.77297974  172.86935425  154.96640015  -11.7194519 ]
80 Cost :  8603.99 
Prediction : 
 [ 248.12785339  276.78305054  172.86924744  154.93840027  -11.6826992 ]
90 Cost :  8602.13 
Predictio

830 Cost :  8469.6 
Prediction : 
 [ 247.30621338  277.52270508  172.87341309  152.87860107   -8.97692966]
840 Cost :  8467.87 
Prediction : 
 [ 247.295578    277.5324707   172.87358093  152.85179138   -8.94129944]
850 Cost :  8466.15 
Prediction : 
 [ 247.28488159  277.54202271  172.87362671  152.82485962   -8.90603447]
860 Cost :  8464.43 
Prediction : 
 [ 247.27418518  277.55184937  172.87367249  152.79804993   -8.87058735]
870 Cost :  8462.71 
Prediction : 
 [ 247.2633667   277.56140137  172.87371826  152.77111816   -8.83538437]
880 Cost :  8461.0 
Prediction : 
 [ 247.25273132  277.57122803  172.87388611  152.74430847   -8.7999382 ]
890 Cost :  8459.28 
Prediction : 
 [ 247.24203491  277.58078003  172.87380981  152.71737671   -8.76473618]
900 Cost :  8457.57 
Prediction : 
 [ 247.2313385   277.59054565  172.8740387   152.69068909   -8.72935104]
910 Cost :  8455.86 
Prediction : 
 [ 247.22058105  277.59997559  172.87384033  152.66363525   -8.69421005]
920 Cost :  8454.15 
Predictio

1920 Cost :  8291.62 
Prediction : 
 [ 246.16677856  278.54916382  172.87948608  150.021698     -5.22287464]
1930 Cost :  8290.08 
Prediction : 
 [ 246.15666199  278.55831909  172.87956238  149.99632263   -5.18941116]
1940 Cost :  8288.54 
Prediction : 
 [ 246.14666748  278.56762695  172.87963867  149.9708252    -5.15582609]
1950 Cost :  8287.0 
Prediction : 
 [ 246.13642883  278.57666016  172.87971497  149.94532776   -5.12248611]
1960 Cost :  8285.47 
Prediction : 
 [ 246.12625122  278.58596802  172.87979126  149.91995239   -5.08902407]
1970 Cost :  8283.92 
Prediction : 
 [ 246.11607361  278.59487915  172.87974548  149.89433289   -5.05562305]
1980 Cost :  8282.39 
Prediction : 
 [ 246.10595703  278.60430908  172.87994385  149.86920166   -5.02216101]
1990 Cost :  8280.85 
Prediction : 
 [ 246.09571838  278.61297607  172.87971497  149.84346008   -4.98894405]
2000 Cost :  8279.33 
Prediction : 
 [ 246.08583069  278.62252808  172.88008118  149.8183136    -4.95536137]


In [15]:
x_data = [[73., 80., 75.,], [93., 88., 93.], [89., 91., 90.],
          [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3]) # None = 인스턴스 값에 제한을 두지 않겠다.
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b # Matrix사용으로 간단해진 수식! W(X) = XW
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {X : x_data, Y : y_data})
    
    if step % 10 == 0 :
        print(step, "Cost : ", cost_val, "\nPrediction : \n" , hy_val)

0 Cost :  135.624 
Prediction : 
 [[ 143.62409973]
 [ 171.35969543]
 [ 169.12632751]
 [ 189.52308655]
 [ 125.82218933]]
10 Cost :  19.0309 
Prediction : 
 [[ 153.16244507]
 [ 182.84564209]
 [ 180.43251038]
 [ 201.83500671]
 [ 134.58866882]]
20 Cost :  18.9739 
Prediction : 
 [[ 153.18000793]
 [ 182.88827515]
 [ 180.46347046]
 [ 201.86843872]
 [ 134.62677002]]
30 Cost :  18.9183 
Prediction : 
 [[ 153.16880798]
 [ 182.89628601]
 [ 180.46029663]
 [ 201.86474609]
 [ 134.63844299]]
40 Cost :  18.8629 
Prediction : 
 [[ 153.15756226]
 [ 182.90415955]
 [ 180.45703125]
 [ 201.86091614]
 [ 134.6499939 ]]
50 Cost :  18.8077 
Prediction : 
 [[ 153.14630127]
 [ 182.91197205]
 [ 180.45376587]
 [ 201.85707092]
 [ 134.66151428]]
60 Cost :  18.7529 
Prediction : 
 [[ 153.13513184]
 [ 182.91981506]
 [ 180.45053101]
 [ 201.853302  ]
 [ 134.67301941]]
70 Cost :  18.6983 
Prediction : 
 [[ 153.12394714]
 [ 182.92759705]
 [ 180.44728088]
 [ 201.8494873 ]
 [ 134.6844635 ]]
80 Cost :  18.6441 
Prediction : 

1020 Cost :  14.5729 
Prediction : 
 [[ 152.19706726]
 [ 183.57685852]
 [ 180.18092346]
 [ 201.51997375]
 [ 135.65196228]]
1030 Cost :  14.5388 
Prediction : 
 [[ 152.18856812]
 [ 183.58279419]
 [ 180.17848206]
 [ 201.51678467]
 [ 135.66096497]]
1040 Cost :  14.505 
Prediction : 
 [[ 152.18013   ]
 [ 183.58872986]
 [ 180.17608643]
 [ 201.51364136]
 [ 135.66993713]]
1050 Cost :  14.4712 
Prediction : 
 [[ 152.17173767]
 [ 183.59468079]
 [ 180.17372131]
 [ 201.51051331]
 [ 135.67893982]]
1060 Cost :  14.4377 
Prediction : 
 [[ 152.16334534]
 [ 183.60057068]
 [ 180.17134094]
 [ 201.50737   ]
 [ 135.68788147]]
1070 Cost :  14.4042 
Prediction : 
 [[ 152.154953  ]
 [ 183.60643005]
 [ 180.16891479]
 [ 201.50418091]
 [ 135.69677734]]
1080 Cost :  14.371 
Prediction : 
 [[ 152.1466217 ]
 [ 183.61231995]
 [ 180.16654968]
 [ 201.50106812]
 [ 135.70568848]]
1090 Cost :  14.3379 
Prediction : 
 [[ 152.13832092]
 [ 183.61817932]
 [ 180.16419983]
 [ 201.49795532]
 [ 135.71456909]]
1100 Cost :  14.30